"""Agent runtime — base agent and registry tests."""

from uuid import uuid4

import pytest
from agent_runtime.agents import AgentStatus
from agent_runtime.agents.base import BaseAgent
from aisc_models import AgentType, Artifact, ArtifactType, TaskContext


class MockAgent(BaseAgent):
    """Test agent that returns a simple artifact."""

    async def generate(self, task: TaskContext) -> Artifact:
        return Artifact(
            project_id=task.project_id,
            task_id=task.task_id,
            type=ArtifactType.PRD,
            name=f"output-from-{self.name}",
            content=f"Generated by {self.name} for task {task.task_id}",
            created_by_agent=self.agent_type.value,
        )


class FailingAgent(BaseAgent):
    """Test agent that always fails."""

    async def generate(self, task: TaskContext) -> Artifact:  # noqa: ARG002
        raise RuntimeError("Simulated failure")


class TestAgentLifecycle:
    def test_initial_status_is_created(self) -> None:
        agent = MockAgent("test-agent", AgentType.REVIEWER)
        assert agent.status == AgentStatus.CREATED

    def test_initialize_transitions_to_idle(self) -> None:
        agent = MockAgent("test-agent", AgentType.REVIEWER)
        import asyncio
        asyncio.run(agent.initialize())
        assert agent.status == AgentStatus.IDLE

    def test_run_transitions_through_statuses(self) -> None:
        agent = MockAgent("test-agent", AgentType.REVIEWER)
        task = TaskContext(
            task_id=uuid4(),
            task_type="test_generation",
            project_id=uuid4(),
            agent_type=AgentType.REVIEWER,
        )
        import asyncio

        async def run_test() -> None:
            await agent.initialize()
            assert agent.status == AgentStatus.IDLE
            result = await agent.run(task)
            assert agent.status == AgentStatus.IDLE
            assert result.name == "output-from-test-agent"

        asyncio.run(run_test())

    def test_run_returns_artifact(self) -> None:
        agent = MockAgent("test-agent", AgentType.REVIEWER)
        task = TaskContext(
            task_id=uuid4(),
            task_type="test_generation",
            project_id=uuid4(),
            agent_type=AgentType.REVIEWER,
        )
        import asyncio

        async def run_test() -> None:
            await agent.initialize()
            result = await agent.run(task)
            assert isinstance(result, Artifact)
            assert result.project_id == task.project_id

        asyncio.run(run_test())

    def test_error_sets_status_to_error(self) -> None:
        agent = FailingAgent("failing-agent", AgentType.DEVELOPER)
        task = TaskContext(
            task_id=uuid4(),
            task_type="test_failure",
            project_id=uuid4(),
            agent_type=AgentType.DEVELOPER,
        )
        import asyncio

        async def run_test() -> None:
            await agent.initialize()
            with pytest.raises(RuntimeError, match="Simulated failure"):
                await agent.run(task)
            assert agent.status == AgentStatus.ERROR

        asyncio.run(run_test())

    def test_to_dict(self) -> None:
        agent = MockAgent("dict-test", AgentType.ARCHITECT)
        d = agent.to_dict()
        assert d["name"] == "dict-test"
        assert d["agent_type"] == "architect"
        assert "status" in d


class TestAgentRegistry:
    def test_register_and_get(self) -> None:
        from agent_runtime.agents.registry import AgentRegistry
        reg = AgentRegistry()
        agent = MockAgent("reg-test", AgentType.ARCHITECT)
        reg.register(agent)
        assert reg.get("reg-test") is agent

    def test_get_by_type(self) -> None:
        from agent_runtime.agents.registry import AgentRegistry
        reg = AgentRegistry()
        pm = MockAgent("pm-1", AgentType.PRODUCT_MANAGER)
        dev = MockAgent("dev-1", AgentType.DEVELOPER)
        reg.register(pm)
        reg.register(dev)
        pms = reg.get_by_type("product_manager")
        assert len(pms) == 1
        assert pms[0].name == "pm-1"

    def test_get_idle_by_type(self) -> None:
        import asyncio

        from agent_runtime.agents.registry import AgentRegistry

        reg = AgentRegistry()
        agent = MockAgent("idle-test", AgentType.QA)
        reg.register(agent)
        asyncio.run(agent.initialize())

        idle = reg.get_idle_by_type("qa")
        assert len(idle) == 1
        assert idle[0].status == AgentStatus.IDLE
